# Config file for automatic testing at travis-ci.org

dist: trusty
sudo: required
language: python
python: 3.6

env:
  - TOX_ENV=py36-django-18
  - TOX_ENV=py35-django-18
  - TOX_ENV=py34-django-18
  - TOX_ENV=py27-django-18
  - TOX_ENV=py36-django-110
  - TOX_ENV=py35-django-110
  - TOX_ENV=py34-django-110
  - TOX_ENV=py27-django-110
  - TOX_ENV=py36-django-111
  - TOX_ENV=py35-django-111
  - TOX_ENV=py34-django-111
  - TOX_ENV=py27-django-111

matrix:
  fast_finish: true

install: pip install -r requirements-test.txt

script: tox -e $TOX_ENV

after_success:
  - codecov -e TOX_ENV
