language: python
python:
  - "2.7"
  - "3.4"
env:
  - DJANGO_VERSION=1.7.*
  - DJANGO_VERSION=1.8.*
  - DJANGO_VERSION=1.9.*
install:
  - "pip install -r requirements.txt"
  - "pip install Django==$DJANGO_VERSION"
script: "python src/runtests.py"
sudo: false
