# Config file for automatic testing at travis-ci.org

dist: xenial
sudo: required
language: python
services:
  - postgresql

addons:
  postgresql: "10"

matrix:
  include:
    - python: 3.5
      env: TOXENV=py35-django-22

    - python: 3.6
      env: TOXENV=py36-django-22
    - python: 3.6
      env: TOXENV=py36-django-30

    - python: 3.7
      env: TOXENV=py37-django-22
    - python: 3.7
      env: TOXENV=py37-django-30

    - python: 3.8
      env: TOXENV=py38-django-22
    - python: 3.8
      env: TOXENV=py38-django-30

  fast_finish: true

install: pip install -r requirements.txt

script: tox

after_success:
  - codecov -e TOX_ENV

deploy:
  provider: pypi
  # PyPI credentials supplied with environment variables from repository settings
  on:
    repo: jjkester/django-auditlog
    branch: stable
    condition: $TOXENV = py38-django-30
  edge: true
